demonstrating single micropython test case
the test case expectation by running this script on the host
counting up 0
counting up 1
counting up 2
counting up 3
counting up 4
counting up 5
counting up 6
counting up 7
counting up 8
counting up 9
counting up 10
counting up 11
counting up 12
counting up 13
counting up 14
counting up 15
counting up 16
counting up 17
counting up 18
counting up 19
end test case
