print("line 1")
print("line 2")
print("line 3")
print("line 3")
print("line 3")
print("line 4")
print("line 4")
print("line 4")
print("line 5")
print("line 5  long long long long long long long long long long long long" + \
      " long long")
print("line 5")
print("line 5")
print("line 6")